# ==============================================================================
# বৈদিক তিথি, নক্ষত্র, যোগ ও করণের শাস্ত্রীয় বৈশিষ্ট্য ও শুভাশুভ মেটাডেটা
# ==============================================================================

# ১. তিথি মেটাডেটা (১-৩০)
TITHI_METADATA = {
    1: {"name": "Pratipada", "swami": {"en": "Agni", "hi": "अग्नि", "bn": "অগ্নি"}, "shreni": "Nanda", "swabhava": "Vridhiprada", "good_for": {"en": "Auspicious for construction, vows, and new beginnings.", "hi": "निर्माण, संकल्प और नए कार्यों के लिए शुभ।", "bn": "নির্মাণ, সংকল্প এবং নতুন কাজের জন্য শুভ।"}},
    2: {"name": "Dwitiya", "swami": {"en": "Brahma", "hi": "ब्रह्मा", "bn": "ব্রহ্মা"}, "shreni": "Bhadra", "swabhava": "Yashaprada", "good_for": {"en": "Good for laying foundations, marriage, and travel.", "hi": "नींव रखने, विवाह और यात्रा के लिए अच्छा है।", "bn": "ভিত্তিপ্রস্তর স্থাপন, বিবাহ এবং ভ্রমণের জন্য শুভ।"}},
    3: {"name": "Tritiya", "swami": {"en": "Gauri", "hi": "गौरी", "bn": "গৌরী"}, "shreni": "Jaya", "swabhava": "Balaprada", "good_for": {"en": "Good for arts, music, and hair cutting.", "hi": "कला, संगीत और मुंडन के लिए अच्छा है।", "bn": "শিল্প, সঙ্গীত এবং মুণ্ডন কাজের জন্য শুভ।"}},
    4: {"name": "Chaturthi", "swami": {"en": "Ganesha", "hi": "गणेश", "bn": "গণেশ"}, "shreni": "Rikta", "swabhava": "Krodhaprada", "good_for": {"en": "Rikta Tithi. Avoid auspicious tasks, good for overcoming enemies.", "hi": "रिक्ता तिथि। शुभ कार्यों से बचें, शत्रुओं पर विजय पाने के लिए अच्छा है।", "bn": "রিক্তা তিথি। শুভ কাজ বর্জনীয়, শত্রু দমনের জন্য ভালো।"}},
    5: {"name": "Panchami", "swami": {"en": "Nagadevata", "hi": "नागदेवता", "bn": "নাগদেবতা"}, "shreni": "Purna", "swabhava": "Lakshmiprada", "good_for": {"en": "Highly auspicious for medicine, learning, and business.", "hi": "औषधि, विद्या और व्यापार के लिए अत्यंत शुभ।", "bn": "ওষুধ, বিদ্যালাভ এবং ব্যবসার জন্য অত্যন্ত শুভ।"}},
    6: {"name": "Shashthi", "swami": {"en": "Kartikeya", "hi": "कार्तिकेय", "bn": "কার্তিকেয়"}, "shreni": "Nanda", "swabhava": "Yashaprada", "good_for": {"en": "Good for meeting leaders, buying vehicles, and health remedies.", "hi": "नेताओं से मिलने, वाहन खरीदने और स्वास्थ्य उपचार के लिए अच्छा है।", "bn": "নেতাদের সাথে সাক্ষাৎ, যানবাহন কেনা এবং চিকিৎসার জন্য শুভ।"}},
    7: {"name": "Saptami", "swami": {"en": "Surya", "hi": "सूर्य", "bn": "সূর্য"}, "shreni": "Bhadra", "swabhava": "Mitraprada", "good_for": {"en": "Auspicious for journeys, buying jewelry, and starting trade.", "hi": "यात्रा, आभूषण खरीदने और व्यापार शुरू करने के लिए शुभ।", "bn": "ভ্রমণ, গহনা কেনা এবং ব্যবসা শুরুর জন্য শুভ।"}},
    8: {"name": "Ashtami", "swami": {"en": "Shiva / Rudra", "hi": "शिव / रुद्र", "bn": "শিব / রুদ্র"}, "shreni": "Jaya", "swabhava": "Dwandvaprada", "good_for": {"en": "Good for spiritual practices, crafts, and defense.", "hi": "आध्यात्मिक अभ्यास, शिल्प और रक्षा कार्यों के लिए अच्छा है।", "bn": "আধ্যাত্মিক সাধনা, শিল্পকর্ম এবং প্রতিরক্ষামূলক কাজের জন্য শুভ।"}},
    9: {"name": "Navami", "swami": {"en": "Durga", "hi": "दुर्गा", "bn": "দুর্গা"}, "shreni": "Rikta", "swabhava": "Akramaka", "good_for": {"en": "Krishna/Shukla Navami, being Rikta Tithi, is excluded from Good Muhurat timings.", "hi": "कृष्ण/शुक्ल नवमी, रिक्ता तिथि होने के कारण, शुभ मुहूर्त से वर्जित है।", "bn": "কৃষ্ণ/শুক্ল নবমী রিক্তা তিথি হওয়ায় শুভ কাজ থেকে বর্জিত।"}},
    10: {"name": "Dashami", "swami": {"en": "Yama", "hi": "यम", "bn": "যম"}, "shreni": "Purna", "swabhava": "Saumya", "good_for": {"en": "Considered good for most auspicious activities, journeys, and religious rites.", "hi": "अधिकांश शुभ कार्यों, यात्राओं और धार्मिक अनुष्ठानों के लिए अच्छा माना जाता है।", "bn": "অধিকাংশ শুভ কাজ, ভ্রমণ এবং ধর্মীয় অনুষ্ঠানের জন্য ভালো।"}},
    11: {"name": "Ekadashi", "swami": {"en": "Vishwedeva", "hi": "विश्वेदेव", "bn": "বিশ্বেদেবা"}, "shreni": "Nanda", "swabhava": "Anandaprada", "good_for": {"en": "Highly spiritual, suitable for fasting, meditation, and charity.", "hi": "अत्यंत आध्यात्मिक, उपवास, ध्यान और दान के लिए उपयुक्त।", "bn": "অত্যন্ত আধ্যাত্মিক, উপবাস, ধ্যান এবং দানের জন্য উপযুক্ত।"}},
    12: {"name": "Dwadashi", "swami": {"en": "Sri Hari Vishnu", "hi": "श्री हरि विष्णु", "bn": "শ্রীহরি বিষ্ণু"}, "shreni": "Bhadra", "swabhava": "Yashaprada", "good_for": {"en": "Auspicious for fulfilling religious vows, study, and ceremonies.", "hi": "धार्मिक व्रतों को पूरा करने, अध्ययन और समारोहों के लिए शुभ।", "bn": "ধর্মীয় ব্রত পালন, বিদ্যাভ্যাস এবং শুভ অনুষ্ঠানের জন্য মঙ্গলজনক।"}},
    13: {"name": "Trayodashi", "swami": {"en": "Kamadeva", "hi": "कामदेव", "bn": "কামদেব"}, "shreni": "Jaya", "swabhava": "Vijayaprada", "good_for": {"en": "Good for sensual arts, wearing new clothes, and friendship.", "hi": "ललित कलाओं, नए वस्त्र धारण करने और मित्रता के लिए अच्छा है।", "bn": "ললিতকলা, নতুন পোশাক পরিধান এবং বন্ধুত্বের জন্য শুভ।"}},
    14: {"name": "Chaturdashi", "swami": {"en": "Shiva", "hi": "शिव", "bn": "শিব"}, "shreni": "Rikta", "swabhava": "Ugra", "good_for": {"en": "Rikta Tithi. Excluded from general auspicious Muhurats, good for Shiva Puja.", "hi": "रिक्ता तिथि। सामान्य शुभ मुहूर्तों से वर्जित, शिव पूजा के लिए उत्तम।", "bn": "রিক্তা তিথি। সাধারণ শুভ কাজ বর্জনীয়, শিব পূজার জন্য উত্তম।"}},
    15: {"name": "Purnima", "swami": {"en": "Chandra", "hi": "चन्द्र", "bn": "চন্দ্র"}, "shreni": "Purna", "swabhava": "Paushtika", "good_for": {"en": "Full Moon. Auspicious for all noble and religious activities.", "hi": "पूर्णिमा। सभी श्रेष्ठ और धार्मिक कार्यों के लिए शुभ।", "bn": "পূর্ণিমা। সমস্ত মহৎ এবং ধর্মীয় কাজের জন্য শুভ।"}},
    30: {"name": "Amavasya", "swami": {"en": "Pitru Gana", "hi": "पितृ गण", "bn": "পিতৃগণ"}, "shreni": "Darsha", "swabhava": "Pitruprada", "good_for": {"en": "Reserved for Pitru Tarpan and Shraddha; avoid worldly ventures.", "hi": "पितृ तर्पण और श्राद्ध के लिए आरक्षित; सांसारिक कार्यों से बचें।", "bn": "পিতৃ তর্পণ এবং শ্রাদ্ধের জন্য নির্দিষ্ট; জাগতিক শুভ কাজ বর্জনীয়।"}}
}

# ২. নক্ষত্র মেটাডেটা (১-২৭)
NAKSHATRA_METADATA = {
    1: {"name": "Ashwini", "swami": {"en": "Ashwini Kumaras", "hi": "अश्विनी कुमार", "bn": "অশ্বিনী কুমার"}, "swabhava": "Kshipra / Laghu", "akrti": "Horse Head", "mukha": "Tiryang Mukha", "eyesight": "Sulochana", "stars": 3, "verdict": {"en": "Auspicious for travel, medicine, learning, and trading.", "hi": "यात्रा, औषधि, विद्या और व्यापार के लिए शुभ।", "bn": "ভ্রমণ, ওষুধ, বিদ্যালাভ এবং ব্যবসার জন্য শুভ।"}},
    2: {"name": "Bharani", "swami": {"en": "Yama", "hi": "यम", "bn": "যম"}, "swabhava": "Ugra / Krura", "akrti": "Yoni", "mukha": "Adho Mukha", "eyesight": "Andhaksha", "stars": 3, "verdict": {"en": "Inauspicious for new beginnings; good for occult, fire rites, and demolitions.", "hi": "नए कार्यों के लिए अशुभ; तंत्र-मंत्र, अग्नि कर्म और ध्वंस कार्यों के लिए अच्छा है।", "bn": "নতুন কাজের জন্য অশুভ; তন্ত্র, অগ্নি কাজ এবং ধ্বংসাত্মক কাজের জন্য ভালো।"}},
    3: {"name": "Krittika", "swami": {"en": "Agni", "hi": "अग्नि", "bn": "অগ্নি"}, "swabhava": "Misra / Sadharana", "akrti": "Razor / Knife", "mukha": "Tiryang Mukha", "eyesight": "Mandaksha", "stars": 6, "verdict": {"en": "Avoid for peace rituals; suitable for metals, debts, and competitive tasks.", "hi": "शांति अनुष्ठानों से बचें; धातुओं, ऋणों और प्रतिस्पर्धात्मक कार्यों के लिए उपयुक्त।", "bn": "শান্তিমূলক কাজ বর্জনীয়; ধাতু, ঋণ এবং প্রতিযোগিতামূলক কাজের জন্য উপযুক্ত।"}},
    4: {"name": "Rohini", "swami": {"en": "Brahma / Prajapati", "hi": "ब्रह्मा / प्रजापति", "bn": "ব্রহ্মা / প্রজাপতি"}, "swabhava": "Sthira / Dhruva", "akrti": "Cart / Chariot", "mukha": "Urdhwa Mukha", "eyesight": "Sulochana", "stars": 5, "verdict": {"en": "Highly auspicious for marriage, construction, trade, and buying assets.", "hi": "विवाह, निर्माण, व्यापार और संपत्ति खरीदने के लिए अत्यंत शुभ।", "bn": "বিবাহ, গৃহনির্মাণ, ব্যবসা এবং সম্পত্তি কেনার জন্য অত্যন্ত শুভ।"}},
    5: {"name": "Mrigashira", "swami": {"en": "Soma / Moon", "hi": "सोम / चन्द्र", "bn": "সোম / চন্দ্র"}, "swabhava": "Mridu", "akrti": "Deer Head", "mukha": "Tiryang Mukha", "eyesight": "Andhaksha", "stars": 3, "verdict": {"en": "Good for friendships, romance, travelling, and artistic endeavors.", "hi": "मित्रता, प्रेम, यात्रा और कलात्मक कार्यों के लिए अच्छा है।", "bn": "বন্ধুত্ব, প্রেম, ভ্রমণ এবং শৈল্পিক কাজের জন্য ভালো।"}},
    6: {"name": "Ardra", "swami": {"en": "Rudra", "hi": "रुद्र", "bn": "রুদ্র"}, "swabhava": "Tikshna / Daruna", "akrti": "Teardrop / Gem", "mukha": "Tiryang Mukha", "eyesight": "Mandaksha", "stars": 1, "verdict": {"en": "Unfavorable for auspicious beginnings; suitable for overcoming hurdles and surgery.", "hi": "शुभ कार्यों के लिए प्रतिकूल; बाधाओं को दूर करने और शल्य चिकित्सा के लिए उपयुक्त।", "bn": "শুভ কাজের জন্য প্রতিকূল; বাধা অতিক্রম এবং অস্ত্রোপচারের জন্য উপযুক্ত।"}},
    7: {"name": "Punarvasu", "swami": {"en": "Aditi", "hi": "अदिति", "bn": "অদিতি"}, "swabhava": "Chara / Chala", "akrti": "House / Bow", "mukha": "Tiryang Mukha", "eyesight": "Sulochana", "stars": 4, "verdict": {"en": "Considered good for most auspicious activities. Included in Good Muhurat timings.", "hi": "अधिकांश शुभ कार्यों के लिए अच्छा माना जाता है। शुभ मुहूर्तों में शामिल है।", "bn": "অধিকাংশ শুভ কাজের জন্য ভালো। শুভ মুহূর্তের অন্তর্ভুক্ত।"}},
    8: {"name": "Pushya", "swami": {"en": "Brihaspati", "hi": "बृहस्पति", "bn": "বৃহস্পতি"}, "swabhava": "Kshipra and Laghu", "akrti": "Arrow / Flower", "mukha": "Urdhwa Mukha", "eyesight": "Andhaksha", "stars": 3, "verdict": {"en": "Supreme for all auspicious activities and new undertakings (Sarvartha Siddhi).", "hi": "सभी शुभ कार्यों और नए उपक्रमों (सर्वार्थ सिद्धि) के लिए सर्वोच्च।", "bn": "সমস্ত শুভ কাজ এবং নতুন উদ্যোগের (সর্বার্থ সিদ্ধি) জন্য সর্বশ্রেষ্ঠ।"}},
    9: {"name": "Ashlesha", "swami": {"en": "Sarpa / Serpents", "hi": "सर्प", "bn": "সর্প"}, "swabhava": "Tikshna", "akrti": "Coiled Serpent", "mukha": "Adho Mukha", "eyesight": "Mandaksha", "stars": 5, "verdict": {"en": "Inauspicious for trade and travel; suitable for poison removal and occult study.", "hi": "व्यापार और यात्रा के लिए अशुभ; विष निवारण और गुप्त विद्या के लिए उपयुक्त।", "bn": "ব্যবসা এবং ভ্রমণের জন্য অশুভ; বিষ নিবারণ এবং গুপ্তবিদ্যার জন্য উপযুক্ত।"}},
    10: {"name": "Magha", "swami": {"en": "Pitrus", "hi": "पितृ", "bn": "পিতৃগণ"}, "swabhava": "Ugra", "akrti": "Royal Throne", "mukha": "Adho Mukha", "eyesight": "Sulochana", "stars": 5, "verdict": {"en": "Good for ancestral rituals, government dealings, and coronation.", "hi": "पैतृक अनुष्ठानों, सरकारी कार्यों और राज्याभिषेक के लिए अच्छा है।", "bn": "পৈতৃক কাজ, সরকারি লেনদেন এবং রাজ্যাভিষেকের জন্য শুভ।"}}
}

# ৩. যোগ মেটাডেটা (১-২৭)
YOGA_METADATA = {
    19: {"name": "Parigha", "swami": {"en": "Vishwakarma", "hi": "विश्वकर्मा", "bn": "বিশ্বকর্মা"}, "nature": "Malefic", "verdict": {"en": "First half duration is considered inauspicious. Excluded from Good Muhurats.", "hi": "प्रथम भाग अशुभ माना जाता है। इसे शुभ मुहूर्तों से बाहर रखा गया है।", "bn": "প্রথম ভাগ অশুভ। এটি শুভ মুহূর্তের তালিকা থেকে বর্জিত।"}},
    20: {"name": "Shiva", "swami": {"en": "Mitra", "hi": "मित्र", "bn": "মিত্র"}, "nature": "Benefic", "verdict": {"en": "Considered good for most auspicious activities.", "hi": "अधिकांश शुभ कार्यों के लिए अच्छा माना जाता है।", "bn": "অধিকাংশ শুভ কাজের জন্য অত্যন্ত মঙ্গলজনক।"}},
    21: {"name": "Siddha", "swami": {"en": "Kartikeya", "hi": "कार्तिकेय", "bn": "কার্তিকেয়"}, "nature": "Benefic", "verdict": {"en": "Grants perfection and fulfillment in all auspicious endeavors.", "hi": "सभी शुभ कार्यों में पूर्णता और सफलता प्रदान करता है।", "bn": "সমস্ত শুভ কাজে পূর্ণতা এবং সাফল্য প্রদান করে।"}}
}

# ৪. করণ মেটাডেটা (১-৬০)
KARANA_METADATA = {
    "Kaulava": {"name": "Kaulava", "swami": {"en": "Mitra", "hi": "मित्र", "bn": "মিত্র"}, "swabhava": "Saumya", "mobility": "Movable", "verdict": {"en": "Considered good for most auspicious activities.", "hi": "अधिकांश शुभ कार्यों के लिए अच्छा माना जाता है।", "bn": "অধিকাংশ শুভ কাজের জন্য ভালো।"}},
    "Taitila": {"name": "Taitila", "swami": {"en": "Vishwakarma", "hi": "विश्वकर्मा", "bn": "বিশ্বকর্মা"}, "swabhava": "Saumya", "mobility": "Movable", "verdict": {"en": "Considered good for most auspicious activities.", "hi": "अधिकांश शुभ कार्यों के लिए अच्छा माना जाता है।", "bn": "অধিকাংশ শুভ কাজের জন্য ভালো।"}},
    "Garaja": {"name": "Garaja", "swami": {"en": "Bhumi", "hi": "भूमि", "bn": "ভূমি"}, "swabhava": "Saumya", "mobility": "Movable", "verdict": {"en": "Considered good for agricultural work and auspicious activities.", "hi": "कृषि कार्यों और शुभ गतिविधियों के लिए अच्छा माना जाता है।", "bn": "কৃষিকাজ এবং শুভ কাজের জন্য মঙ্গলজনক।"}}
}
